/** Declaration file generated by dts-gen */

export = pino_http;

declare function pino_http(opts: any, stream: any): any;

declare namespace pino_http {
    const prototype: {
    };

    const startTime: any;

    namespace stdSerializers {
        function req(req: any): any;

        function res(res: any): any;

        namespace req {
            const prototype: {
            };

        }

        namespace res {
            const prototype: {
            };

        }

    }

}

